### ISSUE TITLE
dvbviewer plugin crashing kodi 18.1 on MAC

### ISSUE THREAD

**Issue by payback007** [kodi-pvr/pvr.dvbviewer#77]
Hi all,

after Kodi-upgrade to Kodi version 18.1 the dvbviewer-plugin is crashing Kodi on startup. Removing dvbviewer-plugin Kodi starts normally.

Kodi-version: 18.1
dvbviewer-plugin: 3.7.11

**Comment by ksooo** [comment]
Without a crash log nobody can help, i'm afraid.

**Comment by manuelm** [comment]
Yep. Also absolutely no information about the platform. And wrong repo -> https://github.com/manuelm/pvr.dvbviewer

**Comment by ksooo** [comment]
I thought upstream for pvr.dvbviewer is kodi-pvr?

**Comment by payback007** [comment]
sorry, moved the issue to

[https://github.com/manuelm/pvr.dvbviewer/issues/39]

**Comment by manuelm** [comment]
Two years ago @MartijnKaijser requested to move the PVRs not directly maintained by Kodi to private repos. See https://github.com/kodi-pvr/pvr.dvbviewer/issues/52#issuecomment-280855662 and the follow ups. However I never received any answer after doing the initial work: https://github.com/kodi-pvr/pvr.dvbviewer/issues/53

**Comment by payback007** [comment]
moved topic to right repo -> I will close the topic.

**Comment by ksooo** [comment]
@manuelm I think we should keep kodi-pvr as upstream repo, for instance to not lose translations. I recently moved pvr.vdr.vnsi upstream back to kodi-pvr, because it got orphaned. Merging back was PITA and I had to find out that the addon in the other repo was missing all tx translations since making the other repo upstream, where the formerly dead version in kodi-pvr had all the tx updates. 🙄

**Comment by manuelm** [comment]
Fine with me. I always appreciate your efforts in keeping all PVRs working after an API change. And I feared I'd have to watch for PVR changes myself.

**Comment by ksooo** [comment]
:-)
